---
- name: centos jenkins
  hosts: jenkins-centos-machines
  become: yes
  become_user: root
  remote_user: attila

  tasks:
  - name: create jenkins directory
    file:
      state: directory
      path: /home/attila/jenkins
      owner: attila
      group: attila
      mode: 0775

  - name: create jenkins-data directory
    file:
      state: directory
      path: /home/attila/jenkins/jenkins-data/jenkins_home
      owner: attila
      group: attila
      mode: 0775
      recurse: yes

  - name: copi docker-compose yml
    copy:
      src: /home/attila/ansible/ansible-test/jenkins/docker-compose.yml
      dest: /home/attila/jenkins/jenkins-data/docker-compose.yml
      owner: attila
      group: attila
      mode: 0755

  - name: copy centos7 folder
    copy:
      src: /home/attila/ansible/ansible-test/jenkins/centos7
      dest: /home/attila/jenkins/jenkins-data/centos7
      owner: attila
      group: attila
      mode: 0755


  - name: reset ssh connection
    meta: reset_connection

  - name: run jenkins service in docker
    community.general.docker_compose:
      project_src: /home/attila/jenkins/jenkins-data
